n1 = int(input("numero 1: "))
n2 = int(input("numero 2: "))
s = (n1+n2)
m = (n1*n2)
d = (n1/n2)
di = (n1//n2)
e = (n1**n2)
print("a soma é igual a {}, o produto é igual a {}  e a divisão é igual a {}".format(s, m, d))
print("divisão inteira {}  e potencia {}".format(di, e))